version: '3.8'

services:
  # Our NestJS Api
  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage from Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/ner/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/ner/src/app
      - /ner/src/app/node_modules/
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # RUN in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: 12345
      PORT: 3000
    ports:
      - 3000:3000
      - 9229: 9229


  # Our Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/ner/frontend/src/app
      - /ner/frontend/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - api

  #The postgres Admin tool if we want to run some custom queries and so on against our database
  postgres_admin:
    image: dpage/pgadmin:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80                  
